### ISSUE TITLE
Question/Bug: database default ttl for database retention with use_ttl policy

### ISSUE THREAD

**Issue by joshuachp** [astarte-platform/astarte_core#84]
I was wondering if is there a default ttl when using the `use_ttl` database rentention policy?

I tried generating a malformed interface with the policy set to `use_ttl` but missing the `ttl` field. Inserting it with astartectl wasn't a problem and the interface returned without the ttl.

<details>

```json
{
  "interface_name": "com.Int",
  "version_major": 0,
  "version_minor": 1,
  "type": "datastream",
  "ownership": "device",
  "aggregation": "individual",
  "mappings": [
    {
      "endpoint": "/fooo",
      "type": "double",
      "reliability": "unreliable",
      "retention": "discard",
      "database_retention_policy": "use_ttl",
      "explicit_timestamp": true
    }
  ]
}
```

</details>

Here doesn't seem to check for the null value https://github.com/astarte-platform/astarte_core/blob/master/lib/astarte_core/mapping.ex#L227

**Comment by Annopaolo** [comment]
Closed by #85 (no default ttl, an interface with `use_ttl` but no `ttl` field is now rejected). TY!
